<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);
//abdf
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<div class="text-gray-700 body-font border-t border-container-darker shadow pb-16">
    <div class="container py-8 mx-auto">

        <div class="bg-gray-100 flex order-first gap-y-16 mb-12 pt-2">
            <?php foreach ($block->getChildNames() as $childName): ?>
                <?= $childName == 'Block1' ? $block->getBlockHtml($childName) : '' ?>
            <?php endforeach; ?>
        </div>

        <div class="order-first gap-y-16 sm:flex">
            <div class="w-full sm:w-3/4">
                <?php foreach ($block->getChildNames() as $childName): ?>
                    <?= $childName == 'Block2' ? $block->getBlockHtml($childName) : '' ?>
                <?php endforeach; ?>
            </div>
            <?php foreach ($block->getChildNames() as $childName): ?>
                <?= $childName !== 'footer-copyright' && $childName !== 'Block1' && $childName !== 'Block2' && $childName !== 'Block5' ? $block->getBlockHtml($childName) : '' ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div class=" px-4 bg-gray-100 border-t border-b border-container justify-between sm:px-40 sm:flex">
        <div class=" py-6 items-center sm:flex-row flex-col">
            <p>
                <?= $block->getChildHtml('copyright') ?>
            </p>
        </div>
        <?php foreach ($block->getChildNames() as $childName): ?>
            <?= $childName == 'Block5' ? $block->getBlockHtml($childName) : '' ?>
        <?php endforeach; ?>
<!--        <div class="py-6 text-sm text-gray-800 sm:ml-6 sm:mt-0 mt-4">-->
<!--            <label class="p-2 border-r-2 border-solid border-gray-200">PRIVCY POLICY</label>-->
<!--            <label class="p-2 border-r-2 border-solid border-gray-200">TERMS OF USE</label>-->
<!--            <label class="p-2">SITE RULES</label>-->
<!--        </div>-->
    </div>
</div>
<!---->
<!--<div class="grid grid-cols-1 md:grid-cols-4">-->
<!--    <div class="mx-4 text-sm text-zinc-400 ">-->
<!--        <label class="block text-xl text-black font-semibold border-b-2 border-black-300">Shop</label>-->
<!--        <span class="block">Smartphones</span>-->
<!--        <span class="block">Men</span>-->
<!--        <span class="block">Children</span>-->
<!--        <span class="block">Accessories</span>-->
<!--        <span class="block">Other</span>-->
<!--    </div>-->
<!--    <div class="mx-4 text-sm text-zinc-400 ">-->
<!--        <label class="block text-xl text-black font-semibold border-b-2 border-black-300">Policies</label>-->
<!--        <span class="block">Terms of service</span>-->
<!--        <span class="block">Privacy</span>-->
<!--        <span class="block">Security</span>-->
<!--        <span class="block">Terms of use</span>-->
<!--    </div>-->
<!--    <div class="mx-4 text-sm text-zinc-400 ">-->
<!--        <label class="block text-xl text-black font-semibold border-b-2 border-black-300">Customer service</label>-->
<!--        <span class="block">Contact us</span>-->
<!--        <span class="block">Feedback</span>-->
<!--        <span class="block">Return policy</span>-->
<!--        <span class="block">Shipping & Tax</span>-->
<!--        <span class="block">International</span>-->
<!--    </div>-->
<!--    <div class="mx-4 text-sm text-zinc-400 ">-->
<!--        <label class="block text-xl text-black font-semibold border-b-2 border-black-300">Connect with us</label>-->
<!--        <span class="block">Twitter</span>-->
<!--        <span class="block">Facebook</span>-->
<!--        <span class="block">Email</span>-->
<!--        <span class="block">Google</span>-->
<!--        <span class="block">Pin it</span>-->
<!--    </div>-->
<!--</div>-->
