<?php

/**
 * @var \Bss\Training\Block\AddPost $block
 * @var \Magento\Framework\Escaper $escaper
 */

?>
<div x-data="addPost()">
    <button @click="open = true" class="py-2 px-4 rounded text-white bg-primary">Add A Post</button>
    <div x-show="open" class="bg-gray-100 min-h-screen align-center min-w-screen p-8">
        <form @submit.prevent="submitPost()" class="bg-white rounded shadow-sm w-3/4 mx-auto p-4 mt-12">
            <div class="px-4 py-2">
                <span class="block font-semibold pb-1">Post ID:</span>
                <input type="text" class="p-2 w-full">
            </div>
            <div class="px-4 py-2">
                <span class="block font-semibold pb-1">Title:</span>
                <input type="text"  class="p-2 w-full">
            </div>
            <div class="px-4 py-2">
                <span class="block font-semibold pb-1">Content:</span>
                <textarea class="p-2 w-full"></textarea>
            </div>
            <div class="flex px-4 py-2 justify-around">
                <button type="submit" class="py-2 px-4 rounded text-white bg-primary">Add Post</button>
                <button class="py-2 px-4 rounded text-white bg-red-500" @click="open =false">Cancel</button>
            </div>
        </form>
    </div>
</div>

<script>
    const addPostUrl = '<?= $escaper->escapeUrl($block->getUrl('bss/training/addpost/')) ?>';
    function addPost() {
        return {
            open: false,
            submitPost: function () {
                fetch(addPostUrl + '?foo=1', {
                    method: "GET"
                })
            }
        }
    }
</script>
