<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductAttributes;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);
/** @var ProductAttributes $attributesViewModel */
$attributesViewModel = $viewModels->require(ProductAttributes::class);
/** @var Product $product */
$product = $productViewModel->getProduct();
?>

<div class="order-2 w-full mb-6 md:w-7/12 md:pl-5 lg:pl-10 md:py-6 lg:w-1/2 md:mb-0">
    <div>
        <?= $block->getChildHtml("product.info.backto") ?>
    </div>
    <h1 class="text-xl mt-4 mb-3 md:text-3xl font-semibold md:font-bold text-gray-900 title-font">
        <?= $escaper->escapeHtml($product->getName()) ?>
    </h1>

    <div class="my-2 cursor-pointer flex"
         onclick="(
              document.getElementById('customer-review-list') ||
              document.getElementById('customer-reviews')).scrollIntoView({behavior: 'smooth'}
              )">
        <?= $block->getChildHtml('product.info.review') ?>
        <div class="ml-4 font-semibold text-black">
            <a class="" href="#review-form">ADD A REVIEW</a>
        </div>

    </div>

    <div>
        <?= $block->getChildHtml("product.info.price") ?>
    </div>
    <?php if ($tierPriceBlock = $block->getChildHtml("product.price.tier")): ?>
        <div class="py-4 my-2 tier-price-container text-sky-500">
            <?= /** @noEscape */ $tierPriceBlock ?>
        </div>
    <?php endif; ?>

    <div class="flex flex-col sm:flex-row justify-between pt-4">
        <?= $block->getChildHtml("product.info.stockstatus") ?>
        <?= $block->getChildHtml("alert.urls") ?>
    </div>
    <div id="product-details" class="pb-4">
        <?php foreach ($block->getAttributes() as $attributeConfig) {
            $attribute = $attributesViewModel->getAttributeFromLayoutConfig($attributeConfig); ?>
            <?php if ($value = $attribute['value'] ?? null) { ?>
                <div class="flex" <?=/* @noEscape */
                $attribute['value'] ?: "" ?>">
                    <span class="font-semibold product-detail-label">
                        <?= $escaper->escapeHtml($attribute['label']) ?>:
                    </span>
                    <span class="ml-2 text-sky-500 product-detail-value">
                        <?= $escaper->escapeHtml($value) ?>
                    </span>
                </div>
            <?php } ?>
        <?php } ?>
    </div>
    <?php if ($Description = $productViewModel->productAttributeHtml($product, $product->getDescription(), 'description')) { ?>
        <div class="mb-4 leading-relaxed product-description prose"><?= /* @noEscape */ $Description ?></div>
    <?php } ?>

    <?= $block->getChildHtml('product.info.form') ?>

    <div class="my-4">
        <div class="mb-4">
            <label class="font-semibold pb-3">QTY:</label>
            <?php if ($product->isSaleable()): ?>
                <?= $block->getChildHtml("product.info.quantity") ?>
            <?php endif; ?>
        </div>
        <div class="mb-4 md:flex">
            <?php if ($product->isSaleable()): ?>
                <?= $block->getChildHtml("product.info.addtocart") ?>
            <?php endif; ?>

            <button type="submit"
                    form="product_contactforsaleprice_form"
                    title="<?= $escaper->escapeHtmlAttr(__('Contact for sale price')) ?>"
                    class="btn bg-black ml-4"
                    id="product-contactforsaleprice-button"
            >
                <span class="hidden sm:block md:hidden lg:block">
                    Contact for sale price
                </span>
            </button>
        </div>
    </div>

    <?php if ($product->isSaleable()): ?>
        <div class="flex mt-4 justify-end">
            <?= $block->getChildHtml('addtocart.shortcut.buttons') ?>
        </div>
    <?php endif; ?>

    <div class="flex mt-4 justify-end">
        <?= $block->getChildHtml('product.info.addtocompare'); ?>
        <?= $block->getChildHtml('product.info.addtowishlist'); ?>
        <?= $block->getChildHtml('product.info.emailtofriend'); ?>
        <?= $block->getChildHtml('product.info.additional.actions'); ?>
    </div>
    <div class="flex border-x-2 border-gray-300">
        <span class="font-semibold my-6 mr-3">SHARE THIS</span>
        <button class="p-2 px-3"><img class="h-8 w-12" src="http://sieuthivp.com//userdata/news/1383796950484.jpg"></button>
        <button class="p-2 px-3"><img class="h-8 w-12" src="https://champcloud.com/wp-content/uploads/2020/03/FBshares.jpg"></button>
        <button class="p-2 px-3"><img class="h-8 w-12" src="https://i.stack.imgur.com/0MW3U.png"></button>
        <button class="p-2 px-3"><img class="h-8 w-12" src="https://www.santiagobarrionuevo.com/wp-content/uploads/2014/05/pin-it.jpg"></button>
    </div>

    <?= $block->getChildHtml("product.info.additional") ?>
</div>
